model = "gpt-5.4"
model_reasoning_effort = "medium"
personality = "pragmatic"
approval_policy = "never"
sandbox_mode = "danger-full-access"

notify = ["/Users/mknopf/code/github/michaelknopf/zshrc/home/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[plugins."github@openai-curated"]
enabled = true

[plugins."sites@openai-bundled"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[projects."/Users/mknopf/code/github/savi/flock"]
trust_level = "trusted"

[projects."/Users/mknopf/code/github/savi/voice-agent"]
trust_level = "trusted"

[projects."/Users/mknopf/code/github/savi/phony"]
trust_level = "trusted"

[projects."/Users/mknopf/code/github/michaelknopf/zshrc"]
trust_level = "trusted"

[projects."/Users/mknopf/code/github/savi/claude-code-plugins"]
trust_level = "trusted"

[mcp_servers.Oracle]
command = "oracle-mcp"

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]

[mcp_servers.playwright-cdp]
command = "npx"
args = ["-y", "@playwright/mcp@latest", "--cdp-endpoint", "http://localhost:9222"]

[mcp_servers.livekit-docs]
url = "https://docs.livekit.io/mcp"

[mcp_servers.node_repl]
args = []
command = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/Codex.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/mknopf/.codex"
CODEX_HOME = "/Users/mknopf/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "5504c0782b5c86b7dd08314045b9843e973a230e1be8f7e2e0ba3716fc63c55e"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.616.81150"
CODEX_CLI_PATH = "/Applications/Codex.app/Contents/Resources/codex"

[desktop]
appearanceTheme = "dark"
appearanceDarkCodeThemeId = "codex"
sansFontSize = 16
codeFontSize = 13
usePointerCursors = true
mac-menu-bar-enabled = false
composerEnterBehavior = "enter"
reviewDelivery = "detached"
preventSleepWhileRunning = true
keepRemoteControlAwakeWhilePluggedIn = true
git-pull-request-merge-method = "squash"

[desktop.appearanceDarkChromeTheme]
accent = "#0169cc"
contrast = 60
ink = "#fcfcfc"
opaqueWindows = false
surface = "#111111"

[desktop.appearanceDarkChromeTheme.fonts]

[desktop.appearanceDarkChromeTheme.semanticColors]
diffAdded = "#00a240"
diffRemoved = "#e02e2a"
skill = "#b06dff"

[desktop.open-in-target-preferences]
global = "intellij"

[desktop.open-in-target-preferences.perPath]
"/Users/mknopf/Documents/New project" = "intellij"
"/Users/mknopf/code/github/savi/flock" = "intellij"

[marketplaces.openai-bundled]
last_updated = "2026-06-25T03:40:18Z"
source_type = "local"
source = "/Users/mknopf/code/github/michaelknopf/zshrc/home/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-06-25T03:40:52Z"
source_type = "local"
source = "/Users/mknopf/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[features]
js_repl = false
